### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by mvmmvm** [mvmmvm/mystory#16]
### 概要
簡単なミステリーゲームが自動で生成され、仲間内で犯人を当て合う、所謂マーダーミステリーの簡単版を体験できるサービスです。
生成中はLINE連携しておくことで、生成後に通知が受け取れます。

### 実装予定の機能
- [ ] ストーリー・キャラクター生成登録機能（非同期）
- [ ] ストーリー一覧機能
- [ ] プレイヤー＆ルーム登録機能
- [ ] プレイヤー一覧機能
- [ ] プレイヤー詳細機能
- [ ] 回答機能
- [ ] 結果表示機能
- [ ] LINE通知機能

### 必要なページ
- [ ] トップ画面
- [ ] プレイヤー登録画面
- [ ] プレイヤー一覧画面
- [ ] プレイヤー詳細画面
- [ ] 投票画面
- [ ] 結果表示画面

**Comment by Tsuchiya2** [comment]
ストーリーポイント5以上のものは、初めて取り組むものや見通しの立っていないものと見受けられました。ストーリーポイント1,2になるまで細かくissue化することで、進捗を感じられながら開発を進められますし、分かっている部分不透明な部分が可視化されるので、ストーリーポイント1,2になるまで細かくissue立てしましょう。

**Comment by mvmmvm** [comment]
ありがとうございます。細かく細分化させていただきました。
ちなみに、MVPリリース時は無い想定でおりましたが、rspecやminitestは必須項目になりますでしょうか？

**Comment by kenchasonakai** [comment]
LGTMです！

> ちなみに、MVPリリース時は無い想定でおりましたが、rspecやminitestは必須項目になりますでしょうか？

MVPリリース時点ではなくても良いと思います！
